name: Test, Build & Deploy on Digital Ocean
on: [push, pull_request]
jobs:
  build:
    name: Run front-end
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: borales/actions-yarn@v2.3.0
        with:
          cmd: install 
      - uses: borales/actions-yarn@v2.3.0
        with:
          cmd: test 
  deploy:
    name: Build & Deploy on Digital Ocean
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: borales/actions-yarn@v2.3.0
        with:
          cmd: install 
      - uses: borales/actions-yarn@v2.3.0
        with:
          cmd: build
      - name: Deploy to Digital Ocean droplet via SSH action
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.DO_HOST }}
          user: ${{ secrets.DO_USER }}
          key: ${{ secrets.DO_KEY }}
          source: 'build/*'
          target: "
          '/var/www/html'
          strip_components: 1